
(define-module (chibi filesystem)
  (export open-input-file-descriptor open-output-file-descriptor
          duplicate-file-descriptor duplicate-file-descriptor-to
          close-file-descriptor renumber-file-descriptor
          delete-file link-file symbolic-link-file rename-file
          directory-files create-directory delete-directory
          file-status
          file-device               file-inode
          file-mode                 file-num-links
          file-owner                file-group
          file-represented-device   file-size
          file-block-size           file-num-blocks
          file-access-time file-modification-time file-change-time
          file-regular?    file-directory?        file-character?
          file-block?      file-fifo?             file-link?
          file-socket?
          )
  (import-immutable (scheme))
  (include-shared "filesystem")
  (include "filesystem.scm"))

