
(define-module (chibi filesystem)
  (export open-input-file-descriptor open-output-file-descriptor
          duplicate-file-descriptor duplicate-file-descriptor-to
          close-file-descriptor renumber-file-descriptor
          delete-file link-file symbolic-link-file rename-file
          directory-files directory-fold create-directory delete-directory
          file-status
          file-device               file-inode
          file-mode                 file-num-links
          file-owner                file-group
          file-represented-device   file-size
          file-block-size           file-num-blocks
          file-access-time file-modification-time file-change-time
          file-regular?    file-directory?        file-character?
          file-block?      file-fifo?             file-link?
          file-socket?     file-exists?
          get-file-descriptor-flags   set-file-descriptor-flags!
          get-file-descriptor-status  set-file-descriptor-status!
          open/read        open/write             open/read-write
          open/create      open/exclusive         open/truncate
          open/append      open/non-block
          is-a-tty?)
  (import-immutable (scheme))
  (include-shared "filesystem")
  (include "filesystem.scm"))

