
(define-module (chibi io)
  (export read-string read-string! write-string read-line write-line
          port-fold port-fold-right port-map
          port->list port->string-list port->sexp-list port->string
          file-position set-file-position! seek/set seek/cur seek/end
          make-custom-input-port make-custom-output-port
          make-null-output-port make-broadcast-port make-concatenated-port
          make-generated-input-port make-filtered-output-port
          make-filtered-input-port)
  (import-immutable (scheme))
  (include-shared "io/io")
  (include "io/io.scm"))
