
(module (chibi net)
  (export sockaddr? address-info? get-address-info
          socket connect bind accept listen
          with-net-io open-net-io
          address-info-family address-info-socket-type address-info-protocol
          address-info-address address-info-address-length address-info-next)
  (import-immutable (scheme))
  (import (chibi filesystem))
  (include-shared "net")
  (include "net.scm"))

