
(define-module (chibi system)
  (export user-information user? user-name user-password
          user-id user-group-id user-gecos user-home user-shell
          current-user-id current-group-id
          current-effective-user-id current-effective-group-id
          set-current-user-id! set-current-effective-user-id!
          set-current-group-id! set-current-effective-group-id!
          current-session-id create-session
          set-root-directory!)
  (import-immutable (scheme))
  (include-shared "system")
  (include "system.scm"))
