
(define-library (chibi snow utils)
  (export copy-file)
  (import (scheme base)
          (scheme file)
          (scheme time)
          (srfi 33)
          (chibi filesystem)
          (chibi pathname)
          (chibi process)
          (chibi snow interface))
  (include "utils.scm"))
