
(define-library (srfi 166 pretty)
  (import (scheme base)
          (scheme char)
          (scheme write)
          (chibi show shared)
          (chibi string)
          (srfi 1)
          (srfi 69)
          (srfi 166 base))
  (export pretty pretty-shared pretty-simply pretty-color)
  (include "pretty.scm"))
