
static const char* sexp_opcode_names_[] =
  {"NOOP", "RAISE", "RESUMECC", "CALLCC", "APPLY1", "TAIL-CALL", "CALL",
   "FCALL0", "FCALL1", "FCALL2", "FCALL3", "FCALL4", "FCALLN",
   "JUMP-UNLESS", "JUMP", "PUSH", "RESERVE", "DROP",
   "GLOBAL-REF", "GLOBAL-KNOWN-REF", "PARAMETER-REF", "STACK-REF",
   "LOCAL-REF", "LOCAL-SET", "CLOSURE-REF", "CLOSURE-VARS",
   "VECTOR-REF", "VECTOR-SET", "VECTOR-LENGTH", 
   "BYTES-REF", "BYTES-SET", "BYTES-LENGTH",
   "STRING-REF", "STRING-SET", "STRING-LENGTH",
   "STRING-CURSOR-NEXT", "STRING-CURSOR-PREV", "STRING-SIZE",
   "MAKE-PROCEDURE", "MAKE-VECTOR",
   "MAKE-EXCEPTION", "AND", "NULL?", "FIXNUM?", "SYMBOL?", "CHAR?",
   "EOF?", "TYPEP", "MAKE", "SLOT-REF", "SLOT-SET",
   "ISA?", "SLOTN-REF", "SLOTN-SET",
   "CAR", "CDR", "SET-CAR", "SET-CDR", "CONS",
   "ADD", "SUB", "MUL", "DIV", "QUOTIENT", "REMAINDER",
   "LT", "LE", "EQN", "EQ", "EXACT->INEXACT", "INEXACT->EXACT",
   "CHAR->INTEGER", "INTEGER->CHAR", "CHAR-UPCASE", "CHAR-DOWNCASE",
   "WRITE-CHAR", "WRITE-STRING", "READ-CHAR", "PEEK-CHAR",
   "YIELD", "FORCE", "RET", "DONE",
  };

const char** sexp_opcode_names = sexp_opcode_names_;
