/* auto-generated by ./symhuff.scm on Sun Feb 25 23:12:52 2007 */

res = c & 7;
c = c >> 3;
if (res == 0) {
  res = c & 3;
  c = c >> 2;
  if (res == 0) {
    res = c & 3;
    c = c >> 2;
    if (res == 0) {
      res = c & 7;
      c = c >> 3;
      if (res == 0) {
        res = c & 3;
        c = c >> 2;
        if (res == 0) {
          res = _huff_tab21[c & 7];
          c = c >> 3;
        } else if ((res = _huff_tab19[res]) == '\x01') {
          res = _huff_tab20[c & 7];
          c = c >> 3;
        }
      } else if (res == 1) {
        res = _huff_tab18[c & 15];
        c = c >> 4;
      } else if (res == 2) {
        res = _huff_tab17[c & 31];
        c = c >> 5;
      } else if (res == 4) {
        res = _huff_tab16[c & 15];
        c = c >> 4;
      } else if (res == 5) {
        res = _huff_tab15[c & 15];
        c = c >> 4;
      } else if ((res = _huff_tab13[res]) == '\x00') {
        res = _huff_tab14[c & 1];
        c = c >> 1;
      }
    } else if ((res = _huff_tab11[res]) == '\x00') {
      res = _huff_tab12[c & 1];
      c = c >> 1;
    }
  } else if ((res = _huff_tab9[res]) == '\x00') {
    res = _huff_tab10[c & 3];
    c = c >> 2;
  }
 } else if (res == 1) {
  res = _huff_tab8[c & 3];
  c = c >> 2;
 } else if (res == 2) {
  res = c & 3;
  c = c >> 2;
  if (res == 0) {
    res = _huff_tab7[c & 3];
    c = c >> 2;
  } else if ((res = _huff_tab5[res]) == '\x00') {
    res = _huff_tab6[c & 1];
    c = c >> 1;
  }
 } else if (res == 4) {
  res = _huff_tab4[c & 1];
  c = c >> 1;
 } else if (res == 5) {
  res = _huff_tab3[c & 1];
  c = c >> 1;
 } else if ((res = _huff_tab1[res]) == '\x00') {
  res = _huff_tab2[c & 1];
  c = c >> 1;
 }

