/* auto-generated by ./symhuff.scm on Sun Feb 25 23:12:52 2007 */

char _huff_tab21[] = {
  '\x01',  '\x00',  '\x03',  '\x00',  '\x02',  '\x00',  '\x04',  '\x00',
};

char _huff_tab19[] = {
  '\x01',     'j',  '\x01',  '\x00',
};

char _huff_tab20[] = {
  '\x05',  '\x09',  '\x07',  '\x0b',  '\x06',  '\x0a',  '\x08',  '\x0c',
};

char _huff_tab18[] = {
     '2',     ':',     '6',     'B',     '4',     '@',     '8',     'D',
     '3',     ';',     '7',     'C',     '5',     'A',     '9',     'E',
};

char _huff_tab17[] = {
  '\x0d',  '\x1d',  '\x15',     '&',  '\x11',     '"',  '\x19',     ',',
  '\x0f',  '\x1f',  '\x17',     '(',  '\x13',     '$',  '\x1b',     '0',
  '\x0e',  '\x1e',  '\x16',    '\'',  '\x12',     '#',  '\x1a',     '.',
  '\x10',  '\x20',  '\x18',     ')',  '\x14',     '%',  '\x1c',     '1',
};

char _huff_tab16[] = {
     'V',     '^',     'Z',     '|',     'X',     '`',    '\\',     '~',
     'W',     '_',     '[',     '}',     'Y',     '{',     ']',  '\x7f',
};

char _huff_tab15[] = {
     'F',     'N',     'J',     'R',     'H',     'P',     'L',     'T',
     'G',     'O',     'K',     'S',     'I',     'Q',     'M',     'U',
};

char _huff_tab13[] = {
  '\x00',  '\x00',  '\x00',     '+',  '\x00',  '\x00',  '\x00',     '/',
};

char _huff_tab14[] = {
     '*',     'z',
};

char _huff_tab11[] = {
  '\x00',     'b',  '\x00',     'x',
};

char _huff_tab12[] = {
     '!',     'k',
};

char _huff_tab9[] = {
  '\x00',     's',  '\x00',     'l',
};

char _huff_tab10[] = {
     'y',     'w',     '<',     'q',
};

char _huff_tab8[] = {
     'p',     '?',     'g',     'u',
};

char _huff_tab7[] = {
     'f',     '>',     '=',     'v',
};

char _huff_tab5[] = {
  '\x00',     'o',  '\x00',     'd',
};

char _huff_tab6[] = {
     'h',     'm',
};

char _huff_tab4[] = {
     'c',     'i',
};

char _huff_tab3[] = {
     'n',     '-',
};

char _huff_tab1[] = {
  '\x00',  '\x00',  '\x00',     'r',  '\x00',  '\x00',  '\x00',     'a',
};

char _huff_tab2[] = {
     'e',     't',
};

