#!/bin/sh

CHIBI=${CHIBI:-chibi-scheme}
if [ -x ./chibi-scheme ] && ! type $CHIBI 2>/dev/null; then
    # convenience for running from dev, notable "make test-snow"
    CHIBI="./chibi-scheme"
    export LD_LIBRARY_PATH=".:${LD_LIBRARY_PATH}"
    export DYLD_LIBRARY_PATH=".:${DYLD_LIBRARY_PATH}"
fi
SCRIPT_DIR=$(dirname $0)
SNOW_SCRIPT=${SNOW_SCRIPT:-$SCRIPT_DIR/snow-chibi.scm}

exec "${CHIBI}" -isnow.img "${SNOW_SCRIPT}" "$@"
