name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-26.04-arm, macos-latest, macos-26-intel]
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: make # assumes GNUMake
      - name: Test
        run: make test-all
      - name: Setup
        run: sudo make install
      - name: Run in PATH
        run: chibi-scheme r7rs-tests.scm
        working-directory: tests
  msys2-build:
    name: msys2-build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            gcc
      - name: Build
        run: msys2 -c "make PLATFORM=msys"
  emscripten-build:
    name: emscripten-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install emscripten
        run: sudo apt install -y emscripten
      - name: Build
        run: |
          emcmake cmake .
          cmake --build .
